# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8f6c7c52a16589d339a16d5aff08072f"
name = "review app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locales,read_products,read_translations,write_cart_transforms,write_locales,write_translations"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
